### ISSUE TITLE
Request for `l2Norm`

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/blaze_tensor#15]
I like to ask blaze_tensor to add support for the `l2Norm` since it is one of the most useful norms in machine learning. A numpy equivalent implementation is:
```py
def l2_norm(x):
    y = np.max(np.sum(x ** 2))
    return np.sqrt(y)
```

**Comment by hkaiser** [comment]
@taless474 Blaze supports various norms already, we can extend their use to 3D. It is however unclear whether the norm is calculated over the whole 3D dataset or applied somewhat differently. Could you elaborate, please?

**Comment by taless474** [comment]
@hkaiser, that is right. the l2Norm is calculated over the whole 3D dataset.
Having a tensor as:
```c++
blaze::DynamicTensor<int> t{
        {{1, 2, 3, 4}, {5, 6, 7, 8}, {9, 10, 11, 12}},
        {{-1, -2, -3, -4}, {-5, -6, -7, -8}, {-9, -10, -11, -12}}};
std::cout << blaze::l2Norm(t) << std::endl;
```
is expected to result in:
```log
36.055512754639892
```
