### ISSUE TITLE
Add support for `mean` operation

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/blaze_tensor#16]
Although blaze has covered several fundamental operations, it does not have an operation to calculate the average. I believe having `mean` calculations can be really helpful. 
As an example, I need to implement some pooling operation. In the simplest case, I have:
```c++
blaze::DynamicTensor<int> t{
        {{1, 2, 3, 4}, {5, 6, 7, 8}, {9, 10, 11, 12}},
        {{-1, -2, -3, -4}, {-5, -6, -7, -8}, {-9, -10, -11, -12}}};

std::size_t filter_depth = 2;
std::size_t filter_height = 2;
std::size_t filter_width = 2;

blaze::DynamicTensor<double> result(t.pages() - filter_depth + 1,
    t.rows() - filter_height + 1, t.columns() - filter_width + 1);

for (std::size_t p = 0; p != result.pages(); ++p)
    for (std::size_t r = 0; r != result.rows(); ++r)
        for (std::size_t c = 0; c != result.columns(); ++c)

            result(p, r, c) = blaze::sum(blaze::subtensor(
                t, p, r, c, filter_depth, filter_height, filter_width));

result /= (filter_depth * filter_height * filter_width);
```
I need to use `blaze::sum` and a division. In more complex cases, the subtensor has a different size for each group of elements of my result tensor and I have to calculate divisions for each case separately.

**Comment by hkaiser** [comment]
@taless474 Isn't `mean` just implementable using `blaze::sum()` (and a division by the size of the subtensor)? Why would be a `blaze::mean` function more efficient than just doing that?
