### ISSUE TITLE
IntegerSequence.h moved from math to util

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/blaze_tensor#55]
The Blaze header IntegerSequence.h moved from blaze/math to blaze/util.  See https://bitbucket.org/blaze-lib/blaze/commits/4cec1773fa38372e24981081dde4da0a2b6bcf25

**Comment by khuck** [comment]
I fixed it, but I don't have permission to submit to this repo.  It's an easy change, just update `blaze/math/IntegerSequence.h` to `blaze/math/IntegerSequence.h`.

**Comment by hkaiser** [comment]
@khuck could you fork this repo, push your change, and create a PR from there, please?

**Comment by khuck** [comment]
I could, but it turns out that Kalus made many other changes to blaze in the last 5 days that have broken blaze_tensor and/or Phylanx.  I am going to change buildbot to build against an older, stable blaze commit.

**Comment by hkaiser** [comment]
@khuck I'll have a look and will see what I can do.

**Comment by khuck** [comment]
@hkaiser FYI, I was able to build against blaze commit fd397e60717c4870d942055496d5b484beac9f1a from November 20.  see https://bitbucket.org/blaze-lib/blaze/commits/fd397e60717c4870d942055496d5b484beac9f1a

**Comment by khuck** [comment]
@hkaiser why did you change the build to debug?

**Comment by hkaiser** [comment]
@khuck I changed it as all of the rest of the CircleCI environment uses Debug builds. This was triggered by a recent change to HPX causing dependent libraries to fail configuring if the build type is different from the one used for HPX.

**Comment by khuck** [comment]
That explains why CI says all the Phylanx builds succeed, but none of the release buildbot builds do - CI doesn’t test commits with a release build. ;)
